# ────────────────────────────────────────────────────────────────────────────
# 1) Just the Docs 설정 지우기 (remote_theme, include_toc 등 전부 삭제)
# ────────────────────────────────────────────────────────────────────────────

# 3) 사이트 기본 정보
title: ""

# 4) (GitHub Pages URL 경로)
baseurl: "/Robot-Barista"
# ────────────────────────────────────────────────────────────────────────────
