# ────────────────────────────────────────────────────────────────────────────
# 1) Just the Docs 설정 지우기 (remote_theme, include_toc 등 전부 삭제)
# ────────────────────────────────────────────────────────────────────────────

# 2) 내장 테마 선택: minima 또는 jekyll-theme-cayman 중 하나
theme: jekyll-theme-cayman

# 3) 사이트 기본 정보
title: "Uncertainty-Aware Opportunistic HLM for Robotics"
description: "Wireless Robotic Systems 연구 페이지"

# 4) (GitHub Pages URL 경로)
baseurl: "/Robot-Barista"
# ────────────────────────────────────────────────────────────────────────────
